name:                tic-tac-toe
version:             0.1.0.0
github:              "zarak/tic-tac-toe"
license:             BSD3
author:              "Zarak Mahmud"
maintainer:          "zarak@hotmail.ca"
copyright:           "2020 Zarak Mahmud"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/zarak/tic-tac-toe#readme>

dependencies:
- base >= 4.7 && < 5
- split
- paint
- text
- random

library:
  source-dirs: src

executables:
  tic-tac-toe-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tic-tac-toe

tests:
  tic-tac-toe-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tic-tac-toe
    - hspec
